version = 1

test_patterns = [
  "**/*_test.go",
  "**/*_mock.go"
]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/LucasCarioca/terra-translate"